spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  h2:
    console:
      enabled: true

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    scope: ${GOOGLE_SCOPE:openid email profile}

  refresh:
    secret: ${REFRESH_HASH_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-seconds: ${JWT_ACCESS_EXPIRE_SECONDS:1800}
  refresh-token-expire-seconds: ${JWT_REFRESH_EXPIRE_SECONDS:1209600}